services:
  server:
    build: ./game_server
    develop:
      watch:
        - action: sync
          path: ./game_server
          target: /usr/src/app
    ports:
      - "8888:8000"
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/app/data
