services:
  game:
    build: ./game_server
    develop:
      watch:
        - action: sync
          path: ./game_server
          target: /usr/src/app
    volumes:
      - type: bind
        source: ./data
        target: /usr/src/app/data
      - type: bind
        source: ./model
        target: /usr/src/app/model
  nginx:
    build: ./nginx
    develop:
      watch:
        - action: sync
          path: ./nginx/public
          target: /public
    ports:
      - "25565:80"